// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get_contact_info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_contact_info_default = defineTool({
  name: "get_contact_info",
  title: "Obtener informaci\xF3n de contacto",
  description: "Devuelve el tel\xE9fono, WhatsApp, sitio web y ubicaci\xF3n de PROTEAM.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            empresa: "PROTEAM SAS",
            telefono: "+57 310 764 3793",
            whatsapp: "https://wa.me/573107643793",
            sitio_web: "https://proteamsas.com",
            pais: "Colombia",
            actividad: "Distribuidor mayorista B2B de prote\xEDna animal (cerdo importado, pollo, v\xEDsceras de res, pescado)."
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/list_products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var CATEGORIES = {
  cerdo: {
    title: "Cerdo Importado",
    accent: "Importado \xB7 Premium",
    items: [
      "Sirloin",
      "Punta chuleta (entera y picada)",
      "Lomo (Ca\xF1\xF3n)",
      "Paticas (Codillos)",
      "Pierna con Hueso"
    ]
  },
  pollo: {
    title: "Pollo",
    accent: "Fresco \xB7 Congelado",
    items: [
      "Colombinas de pollo",
      "Filete de pechuga",
      "Mollejas de pollo",
      "Pechuga Nacional",
      "Pernil"
    ]
  },
  visceras: {
    title: "V\xEDsceras de Res",
    accent: "Calidad garantizada",
    items: [
      "Bofe de res",
      "H\xEDgado de res",
      "Mondongo",
      "Lengua",
      "Patas de Res",
      "Coraz\xF3n"
    ]
  },
  pescado: {
    title: "Pescados y Otros",
    accent: "Mar \xB7 R\xEDo",
    items: ["Bocachico", "Basa Entera", "Basa Picada", "Papas a la Francesa 2.5 Kg"]
  }
};
var list_products_default = defineTool2({
  name: "list_products",
  title: "Listar productos",
  description: "Lista las categor\xEDas y productos que PROTEAM distribuye. Opcionalmente filtra por categor\xEDa (cerdo, pollo, visceras, pescado).",
  inputSchema: {
    category: z.enum(["cerdo", "pollo", "visceras", "pescado"]).optional().describe("Categor\xEDa opcional para filtrar el listado.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const data = category ? { [category]: CATEGORIES[category] } : CATEGORIES;
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }]
    };
  }
});

// src/lib/mcp/tools/list_coverage.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var ROUTES = [
  { id: "uraba", name: "Urab\xE1 Antioque\xF1o", municipalities: ["Apartad\xF3", "Necocl\xED", "Turbo", "Carepa", "Chigorod\xF3"] },
  { id: "costera", name: "Zona Costera", municipalities: ["Arboletes", "Puerto Escondido", "Los C\xF3rdobas", "San Juan de Urab\xE1", "Canalete"] },
  { id: "bajo-cauca", name: "Bajo Cauca y Sabanas", municipalities: ["Caucasia", "Planeta Rica", "Montel\xEDbano", "La Apartada", "Buenavista"] },
  { id: "sabanas", name: "Sabanas de Sucre", municipalities: ["Sincelejo", "Sahag\xFAn", "Corozal", "Chin\xFA", "Sampu\xE9s", "San Marcos", "Guaranda"] },
  { id: "montes-maria", name: "Montes de Mar\xEDa", municipalities: ["Ovejas", "El Carmen de Bol\xEDvar", "San Juan Nepomuceno", "San Jacinto"] },
  { id: "golfo", name: "El Golfo", municipalities: ["Lorica", "San Antero", "Cove\xF1as", "Tol\xFA", "Toluviejo", "San Onofre"] }
];
var list_coverage_default = defineTool3({
  name: "list_coverage",
  title: "Listar cobertura",
  description: "Devuelve las rutas de entrega y municipios cubiertos por PROTEAM en C\xF3rdoba, Sucre, Antioquia y Bol\xEDvar.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(ROUTES, null, 2) }]
  })
});

// src/lib/mcp/tools/whatsapp_lead_link.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var whatsapp_lead_link_default = defineTool4({
  name: "whatsapp_lead_link",
  title: "Generar enlace de WhatsApp para cotizar",
  description: "Genera un enlace de WhatsApp (wa.me) hacia PROTEAM con un mensaje pre-llenado para solicitar cotizaci\xF3n o informaci\xF3n de un negocio.",
  inputSchema: {
    nombre_negocio: z2.string().optional().describe("Nombre del negocio del cliente."),
    ciudad: z2.string().optional().describe("Ciudad del cliente."),
    productos: z2.string().optional().describe("Productos o prote\xEDnas de inter\xE9s."),
    volumen: z2.string().optional().describe("Volumen estimado (kg/semana o similar)."),
    mensaje_extra: z2.string().optional().describe("Notas adicionales al final del mensaje.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: ({ nombre_negocio, ciudad, productos, volumen, mensaje_extra }) => {
    const lines = [
      "Hola PROTEAM, quiero recibir informaci\xF3n para mi negocio.",
      "",
      `Ciudad: ${ciudad ?? ""}`,
      `Tipo de prote\xEDna que necesito: ${productos ?? ""}`,
      `Volumen estimado: ${volumen ?? ""}`,
      `Nombre del negocio: ${nombre_negocio ?? ""}`
    ];
    if (mensaje_extra) lines.push("", mensaje_extra);
    const url = `https://wa.me/573107643793?text=${encodeURIComponent(lines.join("\n"))}`;
    return {
      content: [{ type: "text", text: url }],
      structuredContent: { url }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "proteam-mcp",
  title: "PROTEAM MCP",
  version: "0.1.0",
  instructions: "Herramientas p\xFAblicas de PROTEAM SAS (distribuidor B2B de prote\xEDna animal en Colombia). Usa `list_products` para el cat\xE1logo, `list_coverage` para rutas/municipios, `get_contact_info` para datos de contacto y `whatsapp_lead_link` para generar un enlace de WhatsApp con mensaje pre-llenado.",
  tools: [get_contact_info_default, list_products_default, list_coverage_default, whatsapp_lead_link_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
